### PR TITLE
add docker configuration for running the project

### PR DESCRIPTION
**Pull request by bendrucker**
This gives applicants and reviewers a shared runtime for the project

### CODE REVIEW

**Comment by Jonahss** [comment]
Can we not? Our current system seems nice and open and I don't want to add any friction for the applicants.

**Comment by bendrucker** [comment]
There's no obligation for candidates to use this and I can add a note saying as much to the readme. A lot of people are rolling right through the Node 4 requirement and getting immediately disqualified. This at least gives them a reminder that they didn't follow the directions.

**Comment by Jonahss** [comment]
You know, I've been wondering about this anyways. Why the Node 4 requirement? We don't even use Node 4.

Node 8 becomes the active LTS release at the end of this month. How about updating this challenge to require node 8?

@kmitchell you're always catching candidates who don't conform to the Node 4 requirement. What do you think about raising it to 8?

**Comment by kmitchell** [comment]
I've come to like the Node 4 requirement. It exposes people who don't actually read all of the assignment. If a candidate blatantly ignores either of our measly two requirements (run under Node 4, and make unmodified tests pass) without a good, solid explanation of why they did so, then I think it's a potential indicator that the candidate might struggle to implement a product spec in code while working here. 

We *could* call those two requirements out better (embolden them, turn them into a bulleted list) but I feel like even that doesn't excuse people from missing them in the current README. 

That said, if we're in favor of moving to LTS, we could replace this requirement with something else entirely to satisfy the check for the candidate's attention to detail. Totally open to that.

**Comment by Techwraith** [comment]
Here are my thoughts:

1) I like adding in requirements that show us whether the candidate read
all the way through the readme.
2) I don't like that we're asking people use a 2 year old version of node,
especially when 8 LTS is right around the corner.
3) Putting this in docker, while nice for us and our candidates, takes away
some decision making from our candidates and stops us from evaluating their
project setup.

Here are my recommendations:

1) add a couple other requirements to the readme
2) switch to node 8
3) don't put this in docker

**Comment by bendrucker** [comment]
Alrighty, I'm closing this

**Pull request closed without merging**
